### ISSUE TITLE
nohup 에 문제가 있습니다.

### ISSUE THREAD

**Issue by yoonespi** [iskra3138/colab_seminar#1]
안녕하세요, colab의 OOM문제로 구글링을 하다가 좋은 코드를 발견하게 되어 참조하고 있습니다.

[학습방법2](https://colab.research.google.com/github/iskra3138/colab_seminar/blob/master/colab%EC%97%90%EC%84%9C_KorQuad_%ED%95%99%EC%8A%B5%ED%95%98%EA%B8%B01_GPU.ipynb#scrollTo=OC4_ihaytGUT)를 실행하였더니 아래와 같은 에러가 발생하였습니다.

`nohup: redirecting stderr to stdout`

어떻게 해결할 수 있을까요? 도움을 주실 수 있으신가요?
감사합니다.

**Comment by iskra3138** [comment]
OOM문제가 GPU의 OOM을 말씀하시는 거라면 nohup을 써도 동일한 문제가 발생할 겁니다. (말씀하신 내용은 nohup error는 아닐 거에요. `!cat log_gpu.txt`로 보면 error 가 어디서 났는 지 보실 수 있을 겁니다. 아마 colab환경이 계속 업데이트 되면서 이전코드와의 버전 차이로 생겼을 것 같네요)

GPU OOM 문제는 `train_batch_size`를 낮추시거나, P100 할당 받을 때까지 계속 런타임 초기화를 하셔야 할 것 같습니다. 

그리고 해당 코드가 TF 1.x로 작성되었을 거라  `%tensorflow_version 1.x` 로 Tensorflow 1.X 대로 바꾸셔야 할 거에요. 

감사합니다.

**Comment by yoonespi** [comment]
tensorflow는 1.x버전을 사용 중입니다. 
train_batch_size도 적게 사용 중인데.. 안되네요.. 어렵습니다.
OOM 문제이기 때문에 어쩔 수 없는 것 같군요.
감사합니다.
